INSERT INTO provinsi (id, nama) VALUES ('000', 'test');
INSERT INTO provinsi (id, nama) VALUES ('kode', 'nama');
INSERT INTO provinsi (id, nama) VALUES ('11', 'Aceh');
INSERT INTO provinsi (id, nama) VALUES ('12', 'Sumatera Utara');
INSERT INTO provinsi (id, nama) VALUES ('13', 'Sumatera Barat');
INSERT INTO provinsi (id, nama) VALUES ('14', 'Riau');
INSERT INTO provinsi (id, nama) VALUES ('15', 'Jambi');
INSERT INTO provinsi (id, nama) VALUES ('16', 'Sumatera Selatan');
INSERT INTO provinsi (id, nama) VALUES ('17', 'Bengkulu');
INSERT INTO provinsi (id, nama) VALUES ('18', 'Lampung');
INSERT INTO provinsi (id, nama) VALUES ('19', 'Kepulauan Bangka Belitung');
INSERT INTO provinsi (id, nama) VALUES ('21', 'Kepulauan Riau');
INSERT INTO provinsi (id, nama) VALUES ('31', 'DKI Jakarta');
INSERT INTO provinsi (id, nama) VALUES ('32', 'Jawa Barat');
INSERT INTO provinsi (id, nama) VALUES ('33', 'Jawa Tengah');
INSERT INTO provinsi (id, nama) VALUES ('34', 'DI Yogyakarta');
INSERT INTO provinsi (id, nama) VALUES ('35', 'Jawa Timur');
INSERT INTO provinsi (id, nama) VALUES ('36', 'Banten');
INSERT INTO provinsi (id, nama) VALUES ('51', 'Bali');
INSERT INTO provinsi (id, nama) VALUES ('52', 'Nusa Tenggara Barat');
INSERT INTO provinsi (id, nama) VALUES ('53', 'Nusa Tenggara Timur');
INSERT INTO provinsi (id, nama) VALUES ('61', 'Kalimantan Barat');
INSERT INTO provinsi (id, nama) VALUES ('62', 'Kalimantan Tengah');
INSERT INTO provinsi (id, nama) VALUES ('63', 'Kalimantan Selatan');
INSERT INTO provinsi (id, nama) VALUES ('64', 'Kalimantan Timur');
INSERT INTO provinsi (id, nama) VALUES ('65', 'Kalimantan Utara');
INSERT INTO provinsi (id, nama) VALUES ('71', 'Sulawesi Utara');
INSERT INTO provinsi (id, nama) VALUES ('72', 'Sulawesi Tengah');
INSERT INTO provinsi (id, nama) VALUES ('73', 'Sulawesi Selatan');
INSERT INTO provinsi (id, nama) VALUES ('74', 'Sulawesi Tenggara');
INSERT INTO provinsi (id, nama) VALUES ('75', 'Gorontalo');
INSERT INTO provinsi (id, nama) VALUES ('76', 'Sulawesi Barat');
INSERT INTO provinsi (id, nama) VALUES ('81', 'Maluku');
INSERT INTO provinsi (id, nama) VALUES ('82', 'Maluku Utara');
INSERT INTO provinsi (id, nama) VALUES ('91', 'Papua Barat');
INSERT INTO provinsi (id, nama) VALUES ('92', 'Papua');



-- Kabupaten Kota

INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('001', 'test', '000');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1101', 'KAB. ACEH SELATAN', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1102', 'KAB. ACEH TENGGARA', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1103', 'KAB. ACEH TIMUR', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1104', 'KAB. ACEH TENGAH', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1105', 'KAB. ACEH BARAT', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1106', 'KAB. ACEH BESAR', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1107', 'KAB. PIDIE', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1108', 'KAB. ACEH UTARA', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1109', 'KAB. SIMEULUE', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1110', 'KAB. ACEH SINGKIL', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1111', 'KAB. BIREUEN', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1112', 'KAB. ACEH BARAT DAYA', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1113', 'KAB. GAYO LUES', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1114', 'KAB. ACEH JAYA', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1115', 'KAB. NAGAN RAYA', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1116', 'KAB. ACEH TAMIANG', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1117', 'KAB. BENER MERIAH', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1118', 'KAB. PIDIE JAYA', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1171', 'KOTA BANDA ACEH', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1172', 'KOTA SABANG', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1173', 'KOTA LHOKSEUMAWE', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1174', 'KOTA LANGSA', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1175', 'KOTA SUBULUSSALAM', '11');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1201', 'KAB. TAPANULI TENGAH', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1202', 'KAB. TAPANULI UTARA', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1203', 'KAB. TAPANULI SELATAN', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1204', 'KAB. NIAS', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1205', 'KAB. LANGKAT', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1206', 'KAB. KARO', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1207', 'KAB. DELI SERDANG', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1208', 'KAB. SIMALUNGUN', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1209', 'KAB. ASAHAN', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1210', 'KAB. LABUHANBATU', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1211', 'KAB. DAIRI', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1212', 'KAB. TOBA SAMOSIR', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1213', 'KAB. MANDAILING NATAL', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1214', 'KAB. NIAS SELATAN', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1215', 'KAB. PAKPAK BHARAT', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1216', 'KAB. HUMBANG HASUNDUTAN', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1217', 'KAB. SAMOSIR', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1218', 'KAB. SERDANG BEDAGAI', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1219', 'KAB. BATU BARA', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1220', 'KAB. PADANG LAWAS UTARA', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1221', 'KAB. PADANG LAWAS', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1222', 'KAB. LABUHANBATU SELATAN', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1223', 'KAB. LABUHANBATU UTARA', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1224', 'KAB. NIAS UTARA', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1225', 'KAB. NIAS BARAT', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1271', 'KOTA MEDAN', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1272', 'KOTA PEMATANG SIANTAR', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1273', 'KOTA SIBOLGA', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1274', 'KOTA TANJUNG BALAI', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1275', 'KOTA BINJAI', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1276', 'KOTA TEBING TINGGI', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1277', 'KOTA PADANGSIDIMPUAN', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1278', 'KOTA GUNUNGSITOLI', '12');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1301', 'KAB. PESISIR SELATAN', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1302', 'KAB. SOLOK', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1303', 'KAB. SIJUNJUNG', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1304', 'KAB. TANAH DATAR', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1305', 'KAB. PADANG PARIAMAN', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1306', 'KAB. AGAM', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1307', 'KAB. LIMA PULUH KOTA', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1308', 'KAB. PASAMAN', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1309', 'KAB. KEPULAUAN MENTAWAI', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1310', 'KAB. DHARMASRAYA', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1311', 'KAB. SOLOK SELATAN', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1312', 'KAB. PASAMAN BARAT', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1371', 'KOTA PADANG', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1372', 'KOTA SOLOK', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1373', 'KOTA SAWAHLUNTO', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1374', 'KOTA PADANG PANJANG', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1375', 'KOTA BUKITTINGGI', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1376', 'KOTA PAYAKUMBUH', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1377', 'KOTA PARIAMAN', '13');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1401', 'KAB. KAMPAR', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1402', 'KAB. INDRAGIRI HULU', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1403', 'KAB. BENGKALIS', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1404', 'KAB. INDRAGIRI HILIR', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1405', 'KAB. PELALAWAN', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1406', 'KAB. ROKAN HULU', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1407', 'KAB. ROKAN HILIR', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1408', 'KAB. SIAK', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1409', 'KAB. KUANTAN SINGINGI', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1410', 'KAB. KEPULAUAN MERANTI', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1471', 'KOTA PEKANBARU', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1472', 'KOTA DUMAI', '14');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1501', 'KAB. KERINCI', '15');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1502', 'KAB. MERANGIN', '15');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1503', 'KAB. SAROLANGUN', '15');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1504', 'KAB. BATANGHARI', '15');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1505', 'KAB. MUARO JAMBI', '15');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1506', 'KAB. TANJUNG JABUNG BARAT', '15');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1507', 'KAB. TANJUNG JABUNG TIMUR', '15');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1508', 'KAB. BUNGO', '15');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1509', 'KAB. TEBO', '15');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1571', 'KOTA JAMBI', '15');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1572', 'KOTA SUNGAI PENUH', '15');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1601', 'KAB. OGAN KOMERING ULU', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1602', 'KAB. OGAN KOMERING ILIR', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1603', 'KAB. MUARA ENIM', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1604', 'KAB. LAHAT', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1605', 'KAB. MUSI RAWAS', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1606', 'KAB. MUSI BANYUASIN', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1607', 'KAB. BANYUASIN', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1608', 'KAB. OGAN KOMERING ULU TIMUR', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1609', 'KAB. OGAN KOMERING ULU SELATAN', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1610', 'KAB. OGAN ILIR', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1611', 'KAB. EMPAT LAWANG', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1612', 'KAB. PENUKAL ABAB LEMATANG ILIR', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1613', 'KAB. MUSI RAWAS UTARA', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1671', 'KOTA PALEMBANG', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1672', 'KOTA PAGAR ALAM', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1673', 'KOTA LUBUK LINGGAU', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1674', 'KOTA PRABUMULIH', '16');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1701', 'KAB. BENGKULU SELATAN', '17');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1702', 'KAB. REJANG LEBONG', '17');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1703', 'KAB. BENGKULU UTARA', '17');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1704', 'KAB. KAUR', '17');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1705', 'KAB. SELUMA', '17');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1706', 'KAB. MUKO MUKO', '17');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1707', 'KAB. LEBONG', '17');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1708', 'KAB. KEPAHIANG', '17');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1709', 'KAB. BENGKULU TENGAH', '17');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1771', 'KOTA BENGKULU', '17');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1801', 'KAB. LAMPUNG SELATAN', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1802', 'KAB. LAMPUNG TENGAH', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1803', 'KAB. LAMPUNG UTARA', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1804', 'KAB. LAMPUNG BARAT', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1805', 'KAB. TULANG BAWANG', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1806', 'KAB. TANGGAMUS', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1807', 'KAB. LAMPUNG TIMUR', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1808', 'KAB. WAY KANAN', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1809', 'KAB. PESAWARAN', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1810', 'KAB. PRINGSEWU', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1811', 'KAB. MESUJI', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1812', 'KAB. TULANG BAWANG BARAT', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1813', 'KAB. PESISIR BARAT', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1871', 'KOTA BANDAR LAMPUNG', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1872', 'KOTA METRO', '18');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1901', 'KAB. BANGKA', '19');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1902', 'KAB. BELITUNG', '19');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1903', 'KAB. BANGKA SELATAN', '19');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1904', 'KAB. BANGKA TENGAH', '19');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1905', 'KAB. BANGKA BARAT', '19');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1906', 'KAB. BELITUNG TIMUR', '19');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('1971', 'KOTA PANGKAL PINANG', '19');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('2101', 'KAB. BINTAN', '21');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('2102', 'KAB. KARIMUN', '21');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('2103', 'KAB. NATUNA', '21');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('2104', 'KAB. LINGGA', '21');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('2105', 'KAB. KEPULAUAN ANAMBAS', '21');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('2171', 'KOTA BATAM', '21');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('2172', 'KOTA TANJUNG PINANG', '21');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3101', 'KAB. ADM. KEP. SERIBU', '31');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3171', 'KOTA ADM. JAKARTA PUSAT', '31');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3172', 'KOTA ADM. JAKARTA UTARA', '31');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3173', 'KOTA ADM. JAKARTA BARAT', '31');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3174', 'KOTA ADM. JAKARTA SELATAN', '31');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3175', 'KOTA ADM. JAKARTA TIMUR', '31');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3201', 'KAB. BOGOR', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3202', 'KAB. SUKABUMI', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3203', 'KAB. CIANJUR', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3204', 'KAB. BANDUNG', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3205', 'KAB. GARUT', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3206', 'KAB. TASIKMALAYA', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3207', 'KAB. CIAMIS', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3208', 'KAB. KUNINGAN', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3209', 'KAB. CIREBON', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3210', 'KAB. MAJALENGKA', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3211', 'KAB. SUMEDANG', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3212', 'KAB. INDRAMAYU', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3213', 'KAB. SUBANG', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3214', 'KAB. PURWAKARTA', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3215', 'KAB. KARAWANG', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3216', 'KAB. BEKASI', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3217', 'KAB. BANDUNG BARAT', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3218', 'KAB. PANGANDARAN', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3271', 'KOTA BOGOR', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3272', 'KOTA SUKABUMI', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3273', 'KOTA BANDUNG', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3274', 'KOTA CIREBON', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3275', 'KOTA BEKASI', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3276', 'KOTA DEPOK', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3277', 'KOTA CIMAHI', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3278', 'KOTA TASIKMALAYA', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3279', 'KOTA BANJAR', '32');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3301', 'KAB. CILACAP', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3302', 'KAB. BANYUMAS', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3303', 'KAB. PURBALINGGA', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3304', 'KAB. BANJARNEGARA', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3305', 'KAB. KEBUMEN', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3306', 'KAB. PURWOREJO', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3307', 'KAB. WONOSOBO', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3308', 'KAB. MAGELANG', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3309', 'KAB. BOYOLALI', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3310', 'KAB. KLATEN', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3311', 'KAB. SUKOHARJO', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3312', 'KAB. WONOGIRI', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3313', 'KAB. KARANGANYAR', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3314', 'KAB. SRAGEN', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3315', 'KAB. GROBOGAN', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3316', 'KAB. BLORA', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3317', 'KAB. REMBANG', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3318', 'KAB. PATI', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3319', 'KAB. KUDUS', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3320', 'KAB. JEPARA', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3321', 'KAB. DEMAK', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3322', 'KAB. SEMARANG', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3323', 'KAB. TEMANGGUNG', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3324', 'KAB. KENDAL', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3325', 'KAB. BATANG', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3326', 'KAB. PEKALONGAN', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3327', 'KAB. PEMALANG', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3328', 'KAB. TEGAL', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3329', 'KAB. BREBES', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3371', 'KOTA MAGELANG', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3372', 'KOTA SURAKARTA', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3373', 'KOTA SALATIGA', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3374', 'KOTA SEMARANG', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3375', 'KOTA PEKALONGAN', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3376', 'KOTA TEGAL', '33');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3401', 'KAB. KULON PROGO', '34');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3402', 'KAB. BANTUL', '34');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3403', 'KAB. GUNUNG KIDUL', '34');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3404', 'KAB. SLEMAN', '34');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3471', 'KOTA YOGYAKARTA', '34');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3501', 'KAB. PACITAN', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3502', 'KAB. PONOROGO', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3503', 'KAB. TRENGGALEK', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3504', 'KAB. TULUNGAGUNG', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3505', 'KAB. BLITAR', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3506', 'KAB. KEDIRI', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3507', 'KAB. MALANG', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3508', 'KAB. LUMAJANG', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3509', 'KAB. JEMBER', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3510', 'KAB. BANYUWANGI', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3511', 'KAB. BONDOWOSO', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3512', 'KAB. SITUBONDO', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3513', 'KAB. PROBOLINGGO', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3514', 'KAB. PASURUAN', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3515', 'KAB. SIDOARJO', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3516', 'KAB. MOJOKERTO', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3517', 'KAB. JOMBANG', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3518', 'KAB. NGANJUK', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3519', 'KAB. MADIUN', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3520', 'KAB. MAGETAN', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3521', 'KAB. NGAWI', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3522', 'KAB. BOJONEGORO', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3523', 'KAB. TUBAN', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3524', 'KAB. LAMONGAN', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3525', 'KAB. GRESIK', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3526', 'KAB. BANGKALAN', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3527', 'KAB. SAMPANG', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3528', 'KAB. PAMEKASAN', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3529', 'KAB. SUMENEP', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3571', 'KOTA KEDIRI', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3572', 'KOTA BLITAR', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3573', 'KOTA MALANG', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3574', 'KOTA PROBOLINGGO', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3575', 'KOTA PASURUAN', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3576', 'KOTA MOJOKERTO', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3577', 'KOTA MADIUN', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3578', 'KOTA SURABAYA', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3579', 'KOTA BATU', '35');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3601', 'KAB. PANDEGLANG', '36');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3602', 'KAB. LEBAK', '36');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3603', 'KAB. TANGERANG', '36');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3604', 'KAB. SERANG', '36');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3671', 'KOTA TANGERANG', '36');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3672', 'KOTA CILEGON', '36');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3673', 'KOTA SERANG', '36');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('3674', 'KOTA TANGERANG SELATAN', '36');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5101', 'KAB. JEMBRANA', '51');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5102', 'KAB. TABANAN', '51');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5103', 'KAB. BADUNG', '51');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5104', 'KAB. GIANYAR', '51');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5105', 'KAB. KLUNGKUNG', '51');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5106', 'KAB. BANGLI', '51');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5107', 'KAB. KARANGASEM', '51');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5108', 'KAB. BULELENG', '51');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5171', 'KOTA DENPASAR', '51');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5201', 'KAB. LOMBOK BARAT', '52');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5202', 'KAB. LOMBOK TENGAH', '52');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5203', 'KAB. LOMBOK TIMUR', '52');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5204', 'KAB. SUMBAWA', '52');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5205', 'KAB. DOMPU', '52');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5206', 'KAB. BIMA', '52');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5207', 'KAB. SUMBAWA BARAT', '52');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5208', 'KAB. LOMBOK UTARA', '52');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5271', 'KOTA MATARAM', '52');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5272', 'KOTA BIMA', '52');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5301', 'KAB. KUPANG', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5302', 'KAB TIMOR TENGAH SELATAN', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5303', 'KAB. TIMOR TENGAH UTARA', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5304', 'KAB. BELU', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5305', 'KAB. ALOR', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5306', 'KAB. FLORES TIMUR', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5307', 'KAB. SIKKA', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5308', 'KAB. ENDE', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5309', 'KAB. NGADA', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5310', 'KAB. MANGGARAI', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5311', 'KAB. SUMBA TIMUR', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5312', 'KAB. SUMBA BARAT', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5313', 'KAB. LEMBATA', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5314', 'KAB. ROTE NDAO', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5315', 'KAB. MANGGARAI BARAT', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5316', 'KAB. NAGEKEO', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5317', 'KAB. SUMBA TENGAH', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5318', 'KAB. SUMBA BARAT DAYA', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5319', 'KAB. MANGGARAI TIMUR', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5320', 'KAB. SABU RAIJUA', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5321', 'KAB. MALAKA', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('5371', 'KOTA KUPANG', '53');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6101', 'KAB. SAMBAS', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6102', 'KAB. MEMPAWAH', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6103', 'KAB. SANGGAU', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6104', 'KAB. KETAPANG', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6105', 'KAB. SINTANG', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6106', 'KAB. KAPUAS HULU', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6107', 'KAB. BENGKAYANG', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6108', 'KAB. LANDAK', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6109', 'KAB. SEKADAU', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6110', 'KAB. MELAWI', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6111', 'KAB. KAYONG UTARA', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6112', 'KAB. KUBU RAYA', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6171', 'KOTA PONTIANAK', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6172', 'KOTA SINGKAWANG', '61');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6201', 'KAB. KOTAWARINGIN BARAT', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6202', 'KAB. KOTAWARINGIN TIMUR', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6203', 'KAB. KAPUAS', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6204', 'KAB. BARITO SELATAN', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6205', 'KAB. BARITO UTARA', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6206', 'KAB. KATINGAN', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6207', 'KAB. SERUYAN', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6208', 'KAB. SUKAMARA', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6209', 'KAB. LAMANDAU', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6210', 'KAB. GUNUNG MAS', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6211', 'KAB. PULANG PISAU', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6212', 'KAB. MURUNG RAYA', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6213', 'KAB. BARITO TIMUR', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6271', 'KOTA PALANGKARAYA', '62');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6301', 'KAB. TANAH LAUT', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6302', 'KAB. KOTABARU', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6303', 'KAB. BANJAR', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6304', 'KAB. BARITO KUALA', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6305', 'KAB. TAPIN', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6306', 'KAB. HULU SUNGAI SELATAN', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6307', 'KAB. HULU SUNGAI TENGAH', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6308', 'KAB. HULU SUNGAI UTARA', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6309', 'KAB. TABALONG', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6310', 'KAB. TANAH BUMBU', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6311', 'KAB. BALANGAN', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6371', 'KOTA BANJARMASIN', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6372', 'KOTA BANJARBARU', '63');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6401', 'KAB. PASER', '64');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6402', 'KAB. KUTAI KARTANEGARA', '64');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6403', 'KAB. BERAU', '64');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6407', 'KAB. KUTAI BARAT', '64');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6408', 'KAB. KUTAI TIMUR', '64');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6409', 'KAB. PENAJAM PASER UTARA', '64');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6411', 'KAB. MAHAKAM ULU', '64');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6471', 'KOTA BALIKPAPAN', '64');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6472', 'KOTA SAMARINDA', '64');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6474', 'KOTA BONTANG', '64');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6501', 'KAB. BULUNGAN', '65');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6502', 'KAB. MALINAU', '65');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6503', 'KAB. NUNUKAN', '65');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6504', 'KAB. TANA TIDUNG', '65');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('6571', 'KOTA TARAKAN', '65');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7101', 'KAB. BOLAANG MONGONDOW', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7102', 'KAB. MINAHASA', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7103', 'KAB. KEPULAUAN SANGIHE', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7104', 'KAB. KEPULAUAN TALAUD', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7105', 'KAB. MINAHASA SELATAN', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7106', 'KAB. MINAHASA UTARA', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7107', 'KAB. MINAHASA TENGGARA', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7108', 'KAB. BOLAANG MONGONDOW UTARA', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7109', 'KAB. KEP. SIAU TAGULANDANG BIARO', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7110', 'KAB. BOLAANG MONGONDOW TIMUR', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7111', 'KAB. BOLAANG MONGONDOW SELATAN', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7171', 'KOTA MANADO', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7172', 'KOTA BITUNG', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7173', 'KOTA TOMOHON', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7174', 'KOTA KOTAMOBAGU', '71');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7201', 'KAB. BANGGAI', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7202', 'KAB. POSO', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7203', 'KAB. DONGGALA', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7204', 'KAB. TOLI TOLI', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7205', 'KAB. BUOL', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7206', 'KAB. MOROWALI', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7207', 'KAB. BANGGAI KEPULAUAN', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7208', 'KAB. PARIGI MOUTONG', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7209', 'KAB. TOJO UNA UNA', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7210', 'KAB. SIGI', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7211', 'KAB. BANGGAI LAUT', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7212', 'KAB. MOROWALI UTARA', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7271', 'KOTA PALU', '72');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7301', 'KAB. KEPULAUAN SELAYAR', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7302', 'KAB. BULUKUMBA', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7303', 'KAB. BANTAENG', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7304', 'KAB. JENEPONTO', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7305', 'KAB. TAKALAR', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7306', 'KAB. GOWA', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7307', 'KAB. SINJAI', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7308', 'KAB. BONE', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7309', 'KAB. MAROS', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7310', 'KAB. PANGKAJENE KEPULAUAN', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7311', 'KAB. BARRU', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7312', 'KAB. SOPPENG', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7313', 'KAB. WAJO', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7314', 'KAB. SIDENRENG RAPPANG', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7315', 'KAB. PINRANG', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7316', 'KAB. ENREKANG', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7317', 'KAB. LUWU', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7318', 'KAB. TANA TORAJA', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7322', 'KAB. LUWU UTARA', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7324', 'KAB. LUWU TIMUR', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7326', 'KAB. TORAJA UTARA', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7371', 'KOTA MAKASSAR', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7372', 'KOTA PARE PARE', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7373', 'KOTA PALOPO', '73');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7401', 'KAB. KOLAKA', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7402', 'KAB. KONAWE', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7403', 'KAB. MUNA', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7404', 'KAB. BUTON', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7405', 'KAB. KONAWE SELATAN', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7406', 'KAB. BOMBANA', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7407', 'KAB. WAKATOBI', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7408', 'KAB. KOLAKA UTARA', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7409', 'KAB. KONAWE UTARA', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7410', 'KAB. BUTON UTARA', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7411', 'KAB. KOLAKA TIMUR', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7412', 'KAB. KONAWE KEPULAUAN', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7413', 'KAB. MUNA BARAT', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7414', 'KAB. BUTON TENGAH', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7415', 'KAB. BUTON SELATAN', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7471', 'KOTA KENDARI', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7472', 'KOTA BAU BAU', '74');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7501', 'KAB. GORONTALO', '75');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7502', 'KAB. BOALEMO', '75');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7503', 'KAB. BONE BOLANGO', '75');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7504', 'KAB. PAHUWATO', '75');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7505', 'KAB. GORONTALO UTARA', '75');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7571', 'KOTA GORONTALO', '75');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7601', 'KAB. MAMUJU UTARA', '76');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7602', 'KAB. MAMUJU', '76');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7603', 'KAB. MAMASA', '76');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7604', 'KAB. POLEWALI MANDAR', '76');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7605', 'KAB. MAJENE', '76');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('7606', 'KAB. MAMUJU TENGAH', '76');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8101', 'KAB. MALUKU TENGAH', '81');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8102', 'KAB. MALUKU TENGGARA', '81');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8103', 'KAB MALUKU TENGGARA BARAT', '81');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8104', 'KAB. BURU', '81');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8105', 'KAB. SERAM BAGIAN TIMUR', '81');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8106', 'KAB. SERAM BAGIAN BARAT', '81');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8107', 'KAB. KEPULAUAN ARU', '81');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8108', 'KAB. MALUKU BARAT DAYA', '81');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8109', 'KAB. BURU SELATAN', '81');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8171', 'KOTA AMBON', '81');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8172', 'KOTA TUAL', '81');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8201', 'KAB. HALMAHERA BARAT', '82');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8202', 'KAB. HALMAHERA TENGAH', '82');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8203', 'KAB. HALMAHERA UTARA', '82');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8204', 'KAB. HALMAHERA SELATAN', '82');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8205', 'KAB. KEPULAUAN SULA', '82');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8206', 'KAB. HALMAHERA TIMUR', '82');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8207', 'KAB. PULAU MOROTAI', '82');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8208', 'KAB. PULAU TALIABU', '82');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8271', 'KOTA TERNATE', '82');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('8272', 'KOTA TIDORE KEPULAUAN', '82');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9101', 'KAB. MERAUKE', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9102', 'KAB. JAYAWIJAYA', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9103', 'KAB. JAYAPURA', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9104', 'KAB. NABIRE', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9105', 'KAB. KEPULAUAN YAPEN', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9106', 'KAB. BIAK NUMFOR', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9107', 'KAB. PUNCAK JAYA', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9108', 'KAB. PANIAI', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9109', 'KAB. MIMIKA', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9110', 'KAB. SARMI', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9111', 'KAB. KEEROM', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9112', 'KAB PEGUNUNGAN BINTANG', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9113', 'KAB. YAHUKIMO', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9114', 'KAB. TOLIKARA', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9115', 'KAB. WAROPEN', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9116', 'KAB. BOVEN DIGOEL', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9117', 'KAB. MAPPI', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9118', 'KAB. ASMAT', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9119', 'KAB. SUPIORI', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9120', 'KAB. MAMBERAMO RAYA', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9121', 'KAB. MAMBERAMO TENGAH', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9122', 'KAB. YALIMO', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9123', 'KAB. LANNY JAYA', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9124', 'KAB. NDUGA', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9125', 'KAB. PUNCAK', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9126', 'KAB. DOGIYAI', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9127', 'KAB. INTAN JAYA', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9128', 'KAB. DEIYAI', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9171', 'KOTA JAYAPURA', '91');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9201', 'KAB. SORONG', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9202', 'KAB. MANOKWARI', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9203', 'KAB. FAK FAK', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9204', 'KAB. SORONG SELATAN', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9205', 'KAB. RAJA AMPAT', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9206', 'KAB. TELUK BINTUNI', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9207', 'KAB. TELUK WONDAMA', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9208', 'KAB. KAIMANA', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9209', 'KAB. TAMBRAUW', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9210', 'KAB. MAYBRAT', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9211', 'KAB. MANOKWARI SELATAN', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9212', 'KAB. PEGUNUNGAN ARFAK', '92');
INSERT INTO kabupaten_kota (id, nama, id_provinsi) VALUES ('9271', 'KOTA SORONG', '92');
